---
title: "Evaluate-Samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

### Read in the Alexa Top 1m website list

```{r}
alexa <- read.csv('../alexa-top-1m/top-1m-July.csv')
alexa$url <- as.character(alexa$url)
alexa <- alexa %>% mutate(www_url = ifelse(grepl('^www.', url), url, paste('www.', url, sep='')))
```

### Read in the Alexa top shopping websites

```{r}
alexa_shopping <- read.csv('../alexa-shopping-websites/alexa_shopping_websites_final.csv')
nrow(alexa_shopping)
alexa_shopping$url <- as.character(alexa_shopping$url)
alexa_shopping <- alexa_shopping %>% mutate(www_url = ifelse(grepl('^www.', url), url, paste('www.', url, sep='')))

alexa_shopping <- alexa_shopping %>% filter(overall_rank != 'None')
nrow(alexa_shopping)

alexa_shopping$overall_rank <- as.numeric(as.character(alexa_shopping$overall_rank))
nrow(alexa_shopping)
summary(alexa_shopping$overall_rank)

alexa_shopping <- alexa_shopping %>% filter(overall_rank <= 1000000)
nrow(alexa_shopping)
summary(alexa_shopping$overall_rank)
```

Are these shopping websites in the Top 1m list?

```{r}
summary(alexa_shopping$www_url %in% alexa$www_url)
summary(alexa_shopping[!(alexa_shopping$www_url %in% alexa$www_url), c('url', 'overall_rank')]$overall_rank)

temp <- alexa_shopping[!(alexa_shopping$www_url %in% alexa$www_url), c('url', 'overall_rank')]
temp %>% arrange(overall_rank) %>% select(url, overall_rank)
```