---
title: "Sample-Websites"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

### Create 5 samples of size 100 from the Alexa Top 1m list

```{r}
dat <- read.csv('../alexa-top-1m/top-1m.csv')
nrow(dat)
```

```{r}
for (index in 1:5) {
  dat_sample <- dat[sample(nrow(dat), 100, replace=FALSE), ]
  write.csv(dat_sample, paste('alexa-top-1m-sample', as.character(index), '.csv', sep=''), quote=FALSE, row.names=FALSE)
}
```

### Create 5 samples of size 100 from the Alexa Top 10000 list

```{r}
dat_ten_thousand <- dat[1:10000, ]
nrow(dat_ten_thousand)
```

```{r}
for (index in 1:5) {
  dat_sample <- dat_ten_thousand[sample(nrow(dat_ten_thousand), 100, replace=FALSE), ]
  write.csv(dat_sample, paste('alexa-top-10k-sample', as.character(index), '.csv', sep=''), quote=FALSE, row.names=FALSE)
}
```

### Create 5 samples of size 100 from the Alexa Top Shopping website list

```{r}
dat_shopping <- read.csv('../alexa-shopping-websites/alexa_shopping_websites_final.csv')
```

```{r}
for (index in 1:5) {
  dat_sample <- dat_shopping[sample(nrow(dat_shopping), 100, replace=FALSE), ]
  write.csv(dat_sample, paste('alexa-top-shopping-sample', as.character(index), '.csv', sep=''), quote=FALSE, row.names=FALSE)
}
```